services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  authentication:
    build:
      context: .
      dockerfile: ./apps/authentication/Dockerfile
      target: development
    command: pnpm run start:dev authentication
    env_file:
      - ./apps/authentication/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app

  mysql:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
